# -*- coding: utf-8 -*-
"""TEST1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZY7glR_Fk2OpMFH0wEuSN0WBrVwcaqY
"""

# question no.1
# Print all odd numbers in list
c = int(input("Enter odd numbers"))
for i in range( 1 , c + 1 ):
  if c%2 != 0 :
     print(c)

# question no.3
#reverse a list 1
capital = [ "A" , "B" , "C" , "D" , "E" , "F"]
capital.reverse()
print(capital)

# question no.3
#reverse a list 2
capital = [ "A" , "B" , "C" , "D" , "E" , "F"]
reverser = slice(None, None, -1)
reverse_list = capital[reverser]
print(reverse_list)

# question no.10
#Merge two list
list_1 = [ 1 , 2 , 3 , 4 , 5 , 6 ]
list_2 = [7 , 8 , 9 , 10 ]
for i in list_2:
  list_1.append(i)
print(list_1)

# question no.9
#factorial
num = int(input("Enter a number"))
fact = 1
for i in range(1 , num+1):
  fact *= i
print("the factorial of" , num , "is" , fact)

# question no.8
#vowel or consonant
a = input("Enter value: ")
if a == "a" or a == "e" or  a == "i" or a == "o" or a == "u":
  print("the character you entered is vowel" , a )
else:
  print("the character you entered is consonant" , a )

# question no.5
#the second highest numbers in a list.
t = [ 30 , 2 , 10 , 4 , 5 , 494 , 64 , 88]
num1 = max(t)
for i in t[:] :
  if i == num1 :
    t.remove(i)
print(max(t))

# question no.4 and 6
# sort characters in descending order + the top two maximum numbers in a list +
t = [ 30 , 2 , 10 , 4 , 5 , 494 , 64 , 88]
t.sort(reverse = True)
print(t)
print(t[0] , t[1])

# question no.2
#sum the list
t = [ 30 , 2 , 10 , 4 , 5 , 494 , 64 , 88]
print(sum(t))

# question no.7
#remove repeated characters from a string.

string="life is simple"
p=""
for char in string:
    if char not in p:
        p=p+char
print(p)